title: Home Assistant
views:
  - title: Home
    path: home
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            entity_id:
              - appdaemon.security
            content: >
              **Security**:
              {{ states("appdaemon.security") }}
          - type: entities
            show_header_toggle: false
            entities:
              - input_boolean.sleep
              - input_select.security_override
              - lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked
          - type: entities
            title: Living Room
            show_header_toggle: false
            entities:
              - sensor.multi_sensor_01_2
              - sensor.multi_sensor_01
              - sensor.multi_sensor_01_3
              - entity: switch.mithras_desktop
                icon: mdi:desktop-tower
              - media_player.samsung_smart_tv
              - entity: switch.tradfri_control_outlet_03
                icon: mdi:amplifier
              - entity: switch.tradfri_control_outlet_01
                icon: mdi:speaker-multiple
              - entity: switch.tradfri_control_outlet_02
                icon: mdi:amplifier
              - entity: switch.levoit_humidifier
                icon: mdi:air-humidifier
              - vacuum.roborock_s5
              - vacuum.roomba
          - type: entities
            title: Master Bedroom
            show_header_toggle: false
            entities:
              - sensor.multi_sensor_02
              - sensor.multi_sensor_02_3
              - sensor.multi_sensor_02_2
          - type: entities
            title: Backyard
            show_header_toggle: false
            entities:
              - sensor.mi_flora_temperature
              - sensor.mi_flora_light_intensity
              - sensor.mi_flora_moisture
              - sensor.mi_flora_conductivity

      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.linear_nortek_security_control_llc_gc_tbz48_battery_powered_z_wave_thermostat_mode
          - type: entities
            title: Light
            entities:
              - light.living_room_main
              - light.living_room_back
              - light.kitchen
              - entity: light.on_off_output_7
                icon: mdi:lightbulb-on
              - light.toilet
              - light.hallway_downstairs
              - light.hallway_upstairs
              - light.staircase
              - light.master_bedroom
              - light.master_bathroom
              - entity: light.smart_light_switch_02
                icon: mdi:lightbulb-on
              - light.master_toilet
              - light.landry_room
              - light.porch
              - light.driveway
              - light.garage
              - light.backyard_door
              - light.backyard

      - type: vertical-stack
        cards:
          - type: glance
            show_state: false
            entities:
              - binary_sensor.porch_camera_motion_detected
              - binary_sensor.living_room_camera_motion_detected
              - binary_sensor.motion_sensor_06
              - binary_sensor.motion_sensor_09
              - binary_sensor.motion_sensor_10
              - binary_sensor.motion_sensor_11
              - binary_sensor.motion_sensor_01
              - binary_sensor.motion_sensor_02
              - binary_sensor.motion_sensor_07
              - binary_sensor.motion_sensor_08
              - binary_sensor.motion_sensor_03
              - binary_sensor.motion_sensor_04
              - binary_sensor.motion_sensor_05
              - binary_sensor.motion_sensor_12
              - binary_sensor.motion_sensor_13
              - binary_sensor.door_sensor_03
              - binary_sensor.door_sensor_02
              - binary_sensor.door_sensor_01
          - type: picture-entity
            entity: camera.porch_camera
          - type: picture-entity
            entity: camera.living_room_camera

  - title: Details
    path: details
    cards:
      - type: entities
        title: Person
        show_header_toggle: false
        entities:
          - person.mithras
          - person.diana
      - type: entities
        title: Device
        show_header_toggle: false
        entities:
          - device_tracker.mithras_pixel_3
          - device_tracker.owntracks_mithras
          - device_tracker.diana_pixel_3
          - device_tracker.owntracks_diana
      - type: entities
        title: Camera
        show_header_toggle: false
        entities:
          - binary_sensor.porch_camera_online
          - binary_sensor.living_room_camera_online
      - type: entities
        title: System Monitor
        show_header_toggle: false
        entities:
          - sensor.last_boot
          - sensor.home_assistant_v2_db
          - sensor.processor_use
          - sensor.cpu_temperature
          - sensor.disk_use
          - sensor.disk_free
          - sensor.memory_use
          - sensor.memory_free
          - sensor.network_in_eth0
          - sensor.network_out_eth0
          - sensor.network_throughput_in_eth0
          - sensor.network_throughput_out_eth0
      - type: entities
        title: Battery
        show_header_toggle: false
        entities:
          - sensor.motion_sensor_06_battery_level
          - sensor.motion_sensor_09_battery_level
          - sensor.motion_sensor_10_battery_level
          - sensor.motion_sensor_11_battery_level
          - sensor.motion_sensor_01_battery_level
          - sensor.motion_sensor_02_battery_level
          - sensor.motion_sensor_07_battery_level
          - sensor.motion_sensor_08_battery_level
          - sensor.motion_sensor_03_battery_level
          - sensor.motion_sensor_04_battery_level
          - sensor.motion_sensor_05_battery_level
          - sensor.motion_sensor_12_battery_level
          - sensor.motion_sensor_13_battery_level
          - sensor.door_sensor_02_battery_level
          - sensor.door_sensor_03_battery_level
          - sensor.door_sensor_01_battery_level
          - sensor.multi_sensor_01_battery_level
          - sensor.multi_sensor_02_battery_level
          - sensor.tradfri_on_off_switch_01_battery_level
          - sensor.smart_switch_01_battery_level
          - sensor.mi_magic_cube_01_battery_level
          - sensor.linear_nortek_security_control_llc_gc_tbz48_battery_powered_z_wave_thermostat_battery_level
          - sensor.schlage_allegion_be469zp_connect_smart_deadbolt_battery_level
          - sensor.mi_flora_battery
      - type: entities
        title: Illuminance
        show_header_toggle: false
        entities:
          - sensor.motion_sensor_06
          - sensor.motion_sensor_09
          - sensor.motion_sensor_10
          - sensor.motion_sensor_11
          - sensor.motion_sensor_01
          - sensor.motion_sensor_02
          - sensor.motion_sensor_07
          - sensor.motion_sensor_08
          - sensor.motion_sensor_03
          - sensor.motion_sensor_04
          - sensor.motion_sensor_05
          - sensor.motion_sensor_12
          - sensor.motion_sensor_13

  - title: Graphs
    path: graphs
    cards:
      - type: history-graph
        title: Temperature
        entities:
          - sensor.linear_nortek_security_control_llc_gc_tbz48_battery_powered_z_wave_thermostat_temperature
          - sensor.multi_sensor_01_2
          - sensor.multi_sensor_02
      - type: history-graph
        title: Humidity
        entities:
          - sensor.multi_sensor_01_3
          - sensor.multi_sensor_02_2
      - type: history-graph
        title: Pressure
        entities:
          - sensor.multi_sensor_01
          - sensor.multi_sensor_02_3

  - title: AppDaemon
    path: appdaemon
    cards:
      - type: entities
        title: Front Door Lock
        show_header_toggle: false
        entities:
          - entity: appdaemon_lock.front_door
            name: Code
            icon: mdi:shield
          - type: call-service
            name: Rotate
            service: appdaemon_app.fire_event
            icon: mdi:shield-sync
            service_data:
              event: appdaemon_lock_rotate
              state: front_door
      - type: custom:auto-entities
        card:
          type: entities
          title: AppDaemon
          show_header_toggle: false
        filter:
          include:
            - domain: appdaemon_app
              options:
                icon: mdi:language-python
                type: custom:hui-toggle-entity-row
        sort:
          method: name
      - type: entities
        title: Camera Stats
        show_header_toggle: false
        entities:
          - type: custom:auto-entities
            card:
              type: markdown
              content: |
                {% set count = state_attr("appdaemon_camera_output.stats", "count") %}
                {% set size = (state_attr("appdaemon_camera_output.stats", "size") | int() / 1024 / 1024) | round(2) %}

                **Count: {{ count }}**
                **Size: {{ size }} Mb**
            filter:
              include:
                - entity_id: appdaemon_camera_output.stats
          - type: call-service
            name: Clear
            service: appdaemon_app.fire_event
            icon: mdi:delete
            service_data:
              event: appdaemon_camera_output_clear
      - type: markdown
        title: Camera Snapshots
        content: |
          {% set snapshots = state_attr("appdaemon_camera_output.stats", "snapshots") | from_json %}

          {% for snapshot in snapshots %}
            <a href="{{ snapshot }}" target="_blank">
              <img src="{{ snapshot }}" title="{{ snapshot }}"></img>
            </a>
          {%- endfor %}
        entity_id: appdaemon_camera_output.stats
      - type: markdown
        title: Camera Videos
        content: |
          {% set videos = state_attr("appdaemon_camera_output.stats", "videos") | from_json %}

          {% for video in videos %}
            <a href="{{ video }}" target="_blank">
              <p>{{ video }}</p>
            </a>
          {%- endfor %}
        entity_id: appdaemon_camera_output.stats

  - title: Map
    path: map
    panel: true
    cards:
      - type: map
        hours_to_show: 2
        default_zoom: 12
        entities:
          - person.mithras
          - person.diana
          - zone.home
          - zone.microsoft_building_41
          - zone.pro_club
          - zone.diana_s_home
